In [ ]:
#  SOLUTION TO QUESTION GIVE OF 4X3 MATRIX 

In [9]:
import numpy as np

In [10]:
# 3.1 Representing Data as a Matrix

student_scores = np.array([[80, 70, 90],
                          [60, 85, 75],
                          [95, 88, 92],
                          [70, 60, 65]])
student_scores

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [11]:
# 3.2 Total Scores per Student
row_of_sum1 = np.sum(student_scores, axis=1)
for i, total in enumerate(row_of_sum1, 1):
    print(f"The total score for student{i} is {total}")

The total score for student1 is 240
The total score for student2 is 220
The total score for student3 is 275
The total score for student4 is 195


In [12]:
#3.3 Applying Weights (Scalar Multiplication)
weighted_maths = np.array([2, 1, 1])
weighted_maths = student_scores * weighted_maths
print("Since maths is twice as important as others. Weighted scores is:\n", weighted_maths)

new_score = weighted_maths
print(" ")

row_of_sum2 = np.sum(weighted_maths, axis=1)

for i, total in enumerate(row_of_sum2, 1):
    print(f"Total score for student{i} is {total}")



Since maths is twice as important as others. Weighted scores is:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
 
Total score for student1 is 320
Total score for student2 is 280
Total score for student3 is 370
Total score for student4 is 265


In [13]:
# 3.4 Average score per students (Matrix Operations)

subjects = ["Maths", "English", "Science"]
average_subject = np.mean(new_score, axis=0)

for subject, avg in zip(subjects, average_subject):
    print(f"Average of {subjects} is {avg}")



Average of ['Maths', 'English', 'Science'] is 152.5
Average of ['Maths', 'English', 'Science'] is 75.75
Average of ['Maths', 'English', 'Science'] is 80.5


In [27]:
# Final Grade
weight_vector = [0.5, 0.3, 0.2]
final_grade_1 = student_scores@ weight_vector
final_grade = np.round(final_grade_1, 1)
for i, f in enumerate(final_grade):
    print(f"student {i+1} Finale grade: {f}")

student 1 Finale grade: 79.0
student 2 Finale grade: 70.5
student 3 Finale grade: 92.3
student 4 Finale grade: 66.0


In [28]:
# Comparing student 1 grade and student 2 grade
student_1_grade = final_grade[0]
student_2_grade = final_grade[1]
comparism = student_1_grade - student_2_grade
print(comparism)


8.5


In [ ]:
#   FOR 5X4 MATRIX

In [15]:
import numpy as np

# Showing the students scores matrix (5 students × 4 subjects)
students_scores = np.array([
   [55, 90, 45, 60],  # Student 1
    [80, 90, 95, 75],  # Student 2
    [55, 98, 92, 75],  # Student 3
    [80, 80, 85, 90],  # Student 4
    [85, 88, 60, 90]   # Student 5
])


student_students = ["Student 1", "Student 2", "Student 3", "Student 4", "Student 5"]
student_subjects = ["Math", "English", "Science","Agri", "Pyhsics"]
students = [f"Student {i}" for i in range(1, 6)]



In [16]:
# Now we need to Sum all rows (axis=1)
totals_scores = students_scores.sum(axis=1)
print("<>"*30)
for i, total in enumerate(totals_scores):
    print(f"{students_scores[i]} total = {total}")
print("<>"*30)

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[55 90 45 60] total = 250
[80 90 95 75] total = 340
[55 98 92 75] total = 320
[80 80 85 90] total = 335
[85 88 60 90] total = 323
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


In [17]:
# Question 2: Totals per student  
totals = students_scores.sum(axis=1)
subject_means = students_scores.mean(axis=0)

print("<><><><>><TOTAL SCORES PER STUDENT><><>><><><><><><>><><><>")
for name, total in zip(students, totals_scores):
    print(f"{name}: {totals_scores}")
print("<>"*30)


<><><><>><TOTAL SCORES PER STUDENT><><>><><><><><><>><><><>
Student 1: [250 340 320 335 323]
Student 2: [250 340 320 335 323]
Student 3: [250 340 320 335 323]
Student 4: [250 340 320 335 323]
Student 5: [250 340 320 335 323]
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


In [18]:
# Averages per subject
print("\n=== STUDENT AVERAGE SCORES/SUBJECTS ===")
print("<>"*30)
for subj, avg in zip(subjects, subject_means):
    print(f"{subj}: {avg:.2f}")
print("<>"*30)


=== STUDENT AVERAGE SCORES/SUBJECTS ===
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Maths: 71.00
English: 89.20
Science: 75.40
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


In [19]:
# Question 3Step 3: 2. Suppose one subject (e.g., Science) is 3 times more important than others. (Apply scalar multiplication and recompute totals)
weighted_scores = students_scores.copy()
weighted_scores[:, 2] *= 3   # Multiply Science column by 3
weighted_totals = weighted_scores.sum(axis=1)
weighted_scores

array([[ 55,  90, 135,  60],
       [ 80,  90, 285,  75],
       [ 55,  98, 276,  75],
       [ 80,  80, 255,  90],
       [ 85,  88, 180,  90]])

In [20]:
new_student_totals = np.sum(students_scores, axis=1)
print("-- Weighted Student's Total Score--")
for i, total in enumerate(new_student_totals):
    print(f" student_{i+1} total score: {total}")

-- Weighted Student's Total Score--
 student_1 total score: 250
 student_2 total score: 340
 student_3 total score: 320
 student_4 total score: 335
 student_5 total score: 323


In [21]:
#3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplication. 
new_grade_weight = np.array([0.40,0.20,0.30,0.10])
student_students = students_scores* new_grade_weight
student_students


array([[22. , 18. , 13.5,  6. ],
       [32. , 18. , 28.5,  7.5],
       [22. , 19.6, 27.6,  7.5],
       [32. , 16. , 25.5,  9. ],
       [34. , 17.6, 18. ,  9. ]])

In [23]:
# Final Grade
weight_vector = [0.5, 0.3, 0.2]
final_grade_1 = student_scores @ weight_vector
final_grade = np.round(final_grade_1, 1)
for i, f in enumerate(final_grade):
    print(f"student {i+1} Finale grade: {f}")

student 1 Finale grade: 79.0
student 2 Finale grade: 70.5
student 3 Finale grade: 92.3
student 4 Finale grade: 66.0


In [24]:
# Question 4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject?
difference = students_scores[2] - students_scores[3]

print("Difference (Student 3 - Student 4):", difference)

Difference (Student 3 - Student 4): [-25  18   7 -15]


In [25]:
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
for i, score in enumerate(difference):
    if score > 0:
        print(f"Student 3 has {score} marks above Student 4 in test {subjects[i]}")
    elif score < 0:
        print(f"Student 4 has {abs(score)} marks above Student 3 in test {subjects[i]}")
    else:
        print(f"Student 3 and Student 4 scored the same in test {subjects[i]}")


Student 4 has 25 marks above Student 3 in test Mathematics
Student 3 has 18 marks above Student 4 in test English Language
Student 3 has 7 marks above Student 4 in test Chemistry
Student 4 has 15 marks above Student 3 in test Pyhsics


In [ ]:
 #  ><<<<<<<<<<<<<<<<<< MARK DOWN WITH NUMPY CODE    ><<<<<<<<<<<<<<<<<<<<<<<

In [ ]:
import numpy as np
# Question 1 : 1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total  score and the average per subject. 
# Solution 1: Creating 5×4 scores matrix

student_scores = np.array([
    [55, 90, 45, 60],  
    [80, 90, 95, 75],  
    [55, 98, 92, 75],  
    [80, 80, 85, 90],  
    [85, 88, 60, 90]   
])

student_students = [f"Student {i}" for i in range(1, 6)]
student_subjects = ["Math", "English", "Science", "AGR"]


students_totals = students_scores.sum(axis=1)
student_subject_means = student_scores.mean(axis=0)

print(".....STUDENTS TOTAL SCORES/STUDENT.....")
for name, total in zip(student_students, students_totals):
    print(f"{name}: {total}")

print("\n<><>> STUDENTS AVERAGE SCORES/SUBJECTS><><>")
for subj, avg in zip(subjects, subject_means):
    print(f"{subj}: {avg:.2f}")

# Question2: 2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar multiplication and recompute totals.
weighted_scores = student_scores.copy()
weighted_scores[:, 2] *= 3   # Multiply Science column by 3
weighted_totals = weighted_scores.sum(axis=1)

print("\n><><> WEIGHTED TOTALS (Science* 3) <><>")
for name, total in zip(student_students, weighted_totals):
    print(f"{name}: {total}")

# Question 4: Final grades using weights [0.4, 0.2, 0.3, 0.1]
weights = np.array([0.4, 0.2, 0.3, 0.1])
final_grades = student_scores @ weights 
# matrix multiplication above 

print("\n=== FINAL GRADES (weighted) ===")
for name, grade in zip(student_students, final_grades):
    print(f"{name}: {grade:.2f}")

# Question 5: Compare scores of Student 3 and scores of Student 4 
diff = student_scores[2] - student_scores[3]
print("\n=== COMPARISON (Student 3 - Student 4) ===")
for subj, d in zip(subjects, diff):
    who = "Student 3" if d > 0 else "Student 4" if d < 0 else "Both equal"
    print(f"{subj}: {d} → {who} performed better")


.....STUDENTS TOTAL SCORES/STUDENT.....
Student 1: 250
Student 2: 340
Student 3: 320
Student 4: 335
Student 5: 323

<><>> STUDENTS AVERAGE SCORES/SUBJECTS><><>
Math: 71.00
English: 89.20
Science: 75.40
History: 78.00

><><> WEIGHTED TOTALS (Science* 3) <><>
Student 1: 340
Student 2: 530
Student 3: 504
Student 4: 505
Student 5: 443

=== FINAL GRADES (weighted) ===
Student 1: 59.50
Student 2: 86.00
Student 3: 76.70
Student 4: 82.50
Student 5: 78.60

=== COMPARISON (Student 3 - Student 4) ===
Math: -25 → Student 4 performed better
English: 18 → Student 3 performed better
Science: 7 → Student 3 performed better
History: -15 → Student 4 performed better


In [ ]:
#     ><<<<<<<<<<<<<<<<<<<<<<   MARKDOWN WORKS ><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 

STUDENT ANALYSIS PERFORMANCE WITH LINEAR ALGBERA

student_matrix = [
    [ 74,  80,  89,  78], 
    [100,  83,  84,  85], 
    [ 70,  78,  70,  70], 
    [ 98,  73,  82,  89], 
    [ 82,  91,  77,  91]]

subjects = ["Mathematics", "English Language", "Science", "History"]

student_1 total score: ( 74 + 80 + 89 + 78) = 321
student_2 total score: (100 + 83 + 84 + 85) = 352
student_3 total score: (70 + 78 + 70 + 70) = 288
student_4 total score: (98 + 73 + 82 + 89) = 342
student_5 total score: (82 + 91 + 77 + 91) = 341

Mathematics Average: (74 + 100 + 70 + 98 + 82)/5 = 84.8
English Language Average: (80 + 83 + 78 + 73 + 91)/5 = 81.0
science: (89 + 84 + 70 + 82 + 77)/5 = 80.4
History Average: (78 + 85 + 70 + 89 + 91)/5 = 82.6

Suppose Mathematics is 3 times more important than others. Apply scalar 
multiplication and recompute totals.

subj_weight = [3,1,1,1]
new_student_matrix = student_matrix * subj_weight

Let's define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 

new_grade_weight = [0.40,0.20,0.30,0.10]
student_matrix_2 = student_matrix * new_grade_weight

Comparing Student 3 and Student 4 using vector subtraction.
We check Who performed better in each subject

Math: -25 → Student 4 performed better
English: 18 → Student 3 performed better
Science: 7 → Student 3 performed better
History: -15 → Student 4 performed better