student_matrix = [
    [ 74,  80,  89,  78], 
    [100,  83,  84,  85], 
    [ 70,  78,  70,  70], 
    [ 98,  73,  82,  89], 
    [ 82,  91,  77,  91]]

subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]

student_1 total score: ( 74 + 80 + 89 + 78) = 321
student_2 total score: (100 + 83 + 84 + 85) = 352
student_3 total score: (70 + 78 + 70 + 70) = 288
student_4 total score: (98 + 73 + 82 + 89) = 342
student_5 total score: (82 + 91 + 77 + 91) = 341

Mathematics Average: (74 + 100 + 70 + 98 + 82)/5 = 84.8
English Language Average: (80 + 83 + 78 + 73 + 91)/5 = 81.0
Chemistry Average: (89 + 84 + 70 + 82 + 77)/5 = 80.4
Pyhsics Average: (78 + 85 + 70 + 89 + 91)/5 = 82.6

Suppose Mathematics is 3 times more important than others. Apply scalar 
multiplication and recompute totals.

subj_weight = [3,1,1,1]
new_student_matrix = student_matrix * subj_weight

Let's define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 

new_grade_weight = [0.40,0.20,0.30,0.10]
student_matrix_2 = student_matrix * new_grade_weight

Comparing Student 3 and Student 4 using vector subtraction.
We check Who performed better in each subject

Mathematics - sudent 4 perform better with 28 marks above student 3
English - 


In [ ]:
import numpy as np

In [5]:
matrix_1 = np.array([[80,70,90],
                   [60,85,75],
                   [95,88,92],
                   [70,60,65]])

In [6]:
# Total score per student
student_Total = np.sum(matrix_1, axis=1)
print("-- Total Scores per student --")
for i, total in enumerate(student_Total):
    print(f"Student {i+1} Total Score: {total}")


-- Total Scores per student --
Student 1 Total Score: 240
Student 2 Total Score: 220
Student 3 Total Score: 275
Student 4 Total Score: 195


In [7]:
# Applying weight (scalar multiplicatio)
subjects_list = ["Math", "English", "Science"]
# if Math is twice as important as others
matrix_weight = [2,1,1]
matrix_2 = matrix_1 * matrix_weight
matrix_2

array([[160,  70,  90],
       [120,  85,  75],
       [190,  88,  92],
       [140,  60,  65]])

In [8]:
# Average scope per subject 
matrix_1_mean = np.mean(matrix_1, axis=0)
print("--Student Average Score--")
for i,mean_value in enumerate(matrix_1_mean):
    print(f"{subjects_list[i]} Average Score: {mean_value}")

--Student Average Score--
Math Average Score: 76.25
English Average Score: 75.75
Science Average Score: 80.5


In [21]:
# Final Grade
weight_vector = [0.5, 0.3, 0.2]
final_grade_1 = matrix_2 @ weight_vector
final_grade = np.round(final_grade_1, 1)
for i, f in enumerate(final_grade):
    print(f"student {i+1} Finale grade: {f}")

student 1 Finale grade: 119.0
student 2 Finale grade: 100.5
student 3 Finale grade: 139.8
student 4 Finale grade: 101.0


In [23]:
# Comparing student 1 grade and student 2 grade
student_1_grade = final_grade[0]
student_2_grade = final_grade[1]
comparism = student_1_grade - student_2_grade
print(comparism)


18.5


In [ ]:
student_matrix = np.random.randint(70, 101, size=(5, 4))
student_matrix

array([[ 71, 100,  81,  87],
       [ 71,  89,  86,  92],
       [ 87,  85,  72,  91],
       [ 79,  70,  81,  97],
       [ 74,  91,  79,  95]], dtype=int32)

In [3]:
student_totals = np.sum(student_matrix, axis=1)
print("-- Student's Total Score--")
for i, total in enumerate(student_totals):
    print(f" student_{i+1} total score: {total}")

-- Student's Total Score--
 student_1 total score: 339
 student_2 total score: 338
 student_3 total score: 335
 student_4 total score: 327
 student_5 total score: 339


In [4]:
student_subject_avgs = np.mean(student_matrix, axis=0)
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
print("-- Student's Subjects Average Scores--")
for i, m in enumerate(student_subject_avgs):
    print(f" {subjects[i]} Average: {m}")


-- Student's Subjects Average Scores--
 Mathematics Average: 76.4
 English Language Average: 87.0
 Chemistry Average: 79.8
 Pyhsics Average: 92.4


Suppose Mathematics is 3 times more important than others. Apply scalar 
multiplication and recompute totals.

In [12]:
subj_weight = [3,1,1,1]
new_student_matrix = student_matrix * subj_weight
new_student_matrix


array([[213, 100,  81,  87],
       [213,  89,  86,  92],
       [261,  85,  72,  91],
       [237,  70,  81,  97],
       [222,  91,  79,  95]])

In [6]:
new_student_totals = np.sum(new_student_matrix, axis=1)
print("-- Weighted Student's Total Score--")
for i, total in enumerate(new_student_totals):
    print(f" student_{i+1} total score: {total}")

-- Weighted Student's Total Score--
 student_1 total score: 481
 student_2 total score: 480
 student_3 total score: 509
 student_4 total score: 485
 student_5 total score: 487


Let's define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 

In [7]:
new_grade_weight = np.array([0.40,0.20,0.30,0.10])
student_matrix_2 = student_matrix * new_grade_weight

In [8]:
print(f"Student Weighted Matrix \n")
print(student_matrix_2)

Student Weighted Matrix 

[[28.4 20.  24.3  8.7]
 [28.4 17.8 25.8  9.2]
 [34.8 17.  21.6  9.1]
 [31.6 14.  24.3  9.7]
 [29.6 18.2 23.7  9.5]]


Comparing Student 3 and Student 4 using vector subtraction.
We check Who performed better in each subject

In [9]:
student_3 = student_matrix[2]
studemt_4 = student_matrix[3]

In [10]:
student_compare = student_3 - studemt_4
student_compare

array([ 8, 15, -9, -6], dtype=int32)

In [11]:
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
for i, score in enumerate(student_compare):
    if score > 0:
        print(f"Student 3 has {score} marks above Student 4 in test {subjects[i]}")
    elif score < 0:
        print(f"Student 4 has {abs(score)} marks above Student 3 in test {subjects[i]}")
    else:
        print(f"Student 3 and Student 4 scored the same in test {subjects[i]}")


Student 3 has 8 marks above Student 4 in test Mathematics
Student 3 has 15 marks above Student 4 in test English Language
Student 4 has 9 marks above Student 3 in test Chemistry
Student 4 has 6 marks above Student 3 in test Pyhsics
